- name: Install apt repository key for jenkins
  apt_key:
          url: "{{ jenkins_key_url }}"
          state: present
- name: Configure Jenkins repository
  apt_repository:
          repo: "{{ jenkins_repo }}"
          state: present
- name: Install Jenkins
  apt:
          name: jenkins
          state: present
          update_cache: yes
- name: Start Jenkins service
  service:
          name: jenkins
          state: started
- name: Set Environment variables on jenkins machine
  shell: "{{ item }}"
  with_items:
          - echo "MAVEN_HOME=\"/opt/apache-maven-3.6.3\"" >> /etc/profile
          - echo "JAVA_HOME=\"/usr/lib/jvm/java-8-openjdk-amd64\"" >> /etc/profile
          - echo "PATH=\$JAVA_HOME/bin:\$MAVEN_HOME/bin:\$PATH" >> /etc/profile

